runtime: nodejs12

env_variables:
  GOOGLE_APPLICATION_CREDENTIALS: './secrets/Ripple-Public-1c25c707ebf8.json'
automatic_scaling:
  min_idle_instances: automatic
  max_idle_instances: 1
  min_pending_latency: 3000ms
  max_pending_latency: automatic
